"""
run_secure_marl_agent.py
------------------------
Secure drop-in replacement for run_marl_agent.py.

What changes from the original:
    - Loads each agent's keypair + cert from disk (generated by
      generate_keys.py).
    - Wraps every TrafficSignalAgent with a SecureAgent.
    - Every inter-agent state exchange is signed + hash-verified.
    - Emergency priority is granted ONLY when a validated token is
      present on the incoming lane.
    - A security event log is written to `security_events.log` for
      auditing and demonstrating attack detection.

What DOES NOT change:
    - Control logic (phase selection, reward function).
    - SUMO config, routes, simulation length.
    - Metric collection (same CSVs as before).
"""

import os
import sys
import logging
from pathlib import Path

from cryptography.hazmat.primitives import serialization
from cryptography import x509

from security.crypto_utils import load_private_key, load_public_key
from security.secure_agent import SecureAgent
from security.emergency_auth import EmergencyToken


KEYS_DIR = Path("keys")


# ---------------------------------------------------------------------
# Logging: security events go to both console and file
# ---------------------------------------------------------------------
def setup_logging():
    logger = logging.getLogger("security")
    logger.setLevel(logging.INFO)
    fh = logging.FileHandler("security_events.log", mode="w")
    ch = logging.StreamHandler()
    fmt = logging.Formatter("%(asctime)s  %(levelname)-7s  %(message)s")
    fh.setFormatter(fmt)
    ch.setFormatter(fmt)
    logger.addHandler(fh)
    logger.addHandler(ch)
    return logger


# ---------------------------------------------------------------------
# PKI loading helpers
# ---------------------------------------------------------------------
def load_pem_cert(path: Path) -> x509.Certificate:
    return x509.load_pem_x509_certificate(path.read_bytes())


def load_agent_identity(agent_id: str):
    agent_dir = KEYS_DIR / "agents" / agent_id
    if not agent_dir.exists():
        raise FileNotFoundError(
            f"No keys for {agent_id}. Run: python generate_keys.py --agents {agent_id} ..."
        )
    priv = load_private_key((agent_dir / "private.pem").read_bytes())
    pub = load_public_key((agent_dir / "public.pem").read_bytes())
    cert = load_pem_cert(agent_dir / "cert.pem")
    return priv, pub, cert


def load_all_agent_public_keys(agent_ids: list[str]) -> dict:
    out = {}
    for aid in agent_ids:
        pub = load_public_key((KEYS_DIR / "agents" / aid / "public.pem").read_bytes())
        out[aid] = pub
    return out


# ---------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------
def main():
    logger = setup_logging()

    # Lazy-import traci so the file can be parsed and partially tested
    # without SUMO installed.
    try:
        import traci
        import numpy as np
        from marl_agent import TrafficSignalAgent
    except ImportError as exc:
        logger.error(f"Missing runtime dependency: {exc}")
        sys.exit(1)

    # ---------------- Boot SUMO ----------------
    sumocfg = os.environ.get("SUMOCFG", "final2.sumocfg")
    logger.info(f"Starting SUMO with config {sumocfg}")
    traci.start(["sumo-gui", "-c", sumocfg])

    traffic_lights = list(traci.trafficlight.getIDList())
    logger.info(f"Discovered {len(traffic_lights)} traffic lights: {traffic_lights}")

    # ---------------- Load PKI ----------------
    ca_cert = load_pem_cert(KEYS_DIR / "ca_cert.pem")
    eda_public_key = load_public_key((KEYS_DIR / "eda" / "public.pem").read_bytes())
    eda_private_key = load_private_key((KEYS_DIR / "eda" / "private.pem").read_bytes())
    peer_pubs = load_all_agent_public_keys(traffic_lights)
    logger.info("PKI loaded: CA, EDA keys, and all agent public keys.")

    # ---------------- Build agents ----------------
    agents: dict[str, SecureAgent] = {}
    for tl in traffic_lights:
        priv, pub, cert = load_agent_identity(tl)
        base = TrafficSignalAgent(tl)
        agents[tl] = SecureAgent(
            base_agent=base,
            agent_id=tl,
            private_key=priv,
            certificate=cert,
            ca_cert=ca_cert,
            peer_public_keys={k: v for k, v in peer_pubs.items() if k != tl},
            eda_public_key=eda_public_key,
        )

    # ---------------- Metrics ----------------
    vehicle_counts = {tl: [] for tl in traffic_lights}
    rewards = {tl: [] for tl in traffic_lights}
    attack_attempts_blocked = 0

    # ---------------- Main loop ----------------
    N_STEPS = int(os.environ.get("SIM_STEPS", 37172))
    for step in range(N_STEPS):
        traci.simulationStep()

        # Refresh per-tick authenticated emergency list
        for sec in agents.values():
            sec.clear_emergency_tokens()

        # Check every vehicle that claims to be emergency-type and
        # validate its token (if it has one registered as a vehicle param).
        for vid in traci.vehicle.getIDList():
            if traci.vehicle.getTypeID(vid) != "emergency":
                continue
            try:
                token_json = traci.vehicle.getParameter(vid, "emergency_token")
            except traci.TraCIException:
                token_json = ""
            if not token_json:
                logger.warning(f"Vehicle {vid} claims emergency but has NO token -- priority DENIED")
                attack_attempts_blocked += 1
                continue
            token = EmergencyToken.from_json(token_json)
            # Register with every agent -- each validates independently
            accepted_anywhere = False
            for sec in agents.values():
                ok, reason = sec.register_emergency_token(token)
                if ok:
                    accepted_anywhere = True
                else:
                    logger.warning(f"Token rejected by {sec.agent_id} for {vid}: {reason}")
                    attack_attempts_blocked += 1
            if accepted_anywhere:
                logger.info(f"Emergency authenticated: {vid} ({token.reason_code})")

        # Run each agent's control logic exactly as before
        for sec in agents.values():
            state = sec.base.get_state()
            action = sec.base.choose_action()
            sec.base.apply_action(action)
            reward = sec.base.get_reward()
            vehicle_counts[sec.agent_id].append(state[0])
            rewards[sec.agent_id].append(reward)

        if step % 7435 == 0:
            logger.info(f"==== Step {step} Summary ====")
            for tl in traffic_lights:
                if vehicle_counts[tl]:
                    av = np.mean(vehicle_counts[tl])
                    ar = np.mean(rewards[tl])
                    logger.info(f"  {tl}: Avg Vehicles = {av:.2f}, Avg Reward = {ar:.2f}")
            logger.info(f"  Security events blocked so far: {attack_attempts_blocked}")

    traci.close()
    logger.info(f"Simulation complete. Total security events blocked: {attack_attempts_blocked}")


if __name__ == "__main__":
    main()